### ISSUE TITLE
SocketError getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by masylum** [karmi/monittr#1]
I configured my monittr sinatra application with my current monit instances. When I run the application I get this error instead of the machine name:

'SocketError getaddrinfo: Name or service not known'

I checked with curl and monit urls and credentials were ok.

**Comment by karmi** [comment]
Hi, I've changed the URL format for passing Monit endpoints URL during the weekend, are you running the current master version? Are you sure you are passing the URLs in the following format?

```
set :monit_urls, %w[ http://user:password@example.com:2812 ]
```

**Comment by masylum** [comment]
I was not able to install it from source:

<pre>no such file to load -- bundler</pre>

Although I did <pre>gem install bundler</pre>

... so I was using the gem instead.

I'm using the proper format and I checked with curl and the urls are valid and fully working. I'm running my monits using port 1812, but this shouldn't be an issue.

**Comment by karmi** [comment]
I have checked on a clean Ubunu install and it works properly. Be sure to follow these steps:

```
$ sudo gem install monittr --version=0.0.4
# If neccessary, install any dependencies for nokogiri:
# sudo apt-get install libxml2 libxml2-dev libxslt1-dev

$ gem which monittr
$ cd /usr/local/lib/ruby/gems/1.8/gems/monittr-0.0.4 # Or your location

# Run Monit with the example config
$ monit -I -c examples/monitrc

# Comment out the fakeweb lines and customize the URL
$ sudo vim examples/application.rb

# Launch the application
$ ruby examples/application.rb
```

It should be running on http://<YOUR HOST>:4567/

**Comment by masylum** [comment]
I reinstalled the gem with --version=0.0.4 and it works! Thanks! Awesome gem!

**Comment by karmi** [comment]
Great, I'm glad it worked.
